# .github/workflows/merge.yml

name: Merge upstream branches
on:
  schedule:
    - cron:  '*/30 * * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures all history is fetched

      - name: Configure Git
        run: |
          git config user.name 'jd'
          git config user.email '28711824+jewdev@users.noreply.github.com'

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Vendicated/Vencord.git || echo "Remote 'upstream' already exists"

      - name: Fetch from upstream
        run: |
          git fetch upstream +refs/heads/*:refs/remotes/upstream/*

      - name: Checkout and merge main branch
        run: |
          if git ls-remote --heads upstream main; then
            git checkout main
            git merge --no-edit upstream/main
            git push origin main
          else
            echo "Branch 'main' does not exist on upstream, skipping..."
          fi
