# .github/workflows/merge.yml

name: Merge upstream branches
on:
  schedule:
    - cron:  '*/30 * * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures all history is fetched

      - name: Configure Git
        run: |
          git config user.name 'jd'
          git config user.email '28711824+jewdev@users.noreply.github.com'

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Vendicated/Vencord.git || echo "Remote 'upstream' already exists"

      - name: Fetch from upstream
        run: |
          git fetch upstream +refs/heads/*:refs/remotes/upstream/*

      - name: Checkout feature/x branch
        run: |
          git checkout -b feature/x --track upstream/feature/x || git checkout feature/x

      - name: Merge upstream changes into feature branch
        run: |
          git merge --no-edit upstream/feature/x
          git push origin feature/x

      - name: Merge upstream changes into master branch
        run: |
          git checkout master
          git merge --no-edit upstream/master
          git push origin master
